package com.example.scoutquest.ui.navigation

const val MainScreenRoute = "/mainscreen"
const val Profile = "/profile"
const val Settings = "/settings"
const val NewGame = "/newgame"
const val Creator = "/creator"
const val Login = "/login"
const val Register = "/register"
const val JoinGame = "/joingame"
const val AddTask = "/addtask"
const val CreateQuiz = "/createquiz"
const val CreateNote = "/createnote"
const val Browser = "/browser"
const val CreateTrueFalse = "/createtruefalse"
const val UserBrowser = "/userbrowser"
const val GameMap = "/gamemap"
const val CreateOpenQuestion = "/createopenquestion"
const val CreatePhotoTask = "/createphototask"

